// Service worker — handles task queue and tab orchestration
importScripts('config.js');

let stopRequested = false;

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function randomDelay() {
  const ms = CONFIG.DELAY_MIN_MS +
    Math.random() * (CONFIG.DELAY_MAX_MS - CONFIG.DELAY_MIN_MS);
  return sleep(ms);
}

function sendProgress(text) {
  chrome.runtime.sendMessage({ type: 'PROGRESS_UPDATE', text }).catch(() => {});
}

function sendDone(text) {
  chrome.storage.local.set({ taskRunning: false });
  chrome.runtime.sendMessage({ type: 'TASK_DONE', text }).catch(() => {});
  chrome.notifications.create({
    type: 'basic',
    iconUrl: 'icon.png',
    title: 'XHS Insight',
    message: text,
  });
}

/**
 * Wait for a tab to reach status 'complete', with a timeout fallback.
 * XHS is a SPA; for in-page navigation the browser may never fire
 * status='complete', so we resolve after `timeout` ms regardless.
 */
function waitForLoad(tabId, timeout = 12000) {
  return new Promise(resolve => {
    const timer = setTimeout(() => {
      chrome.tabs.onUpdated.removeListener(listener);
      console.warn(`[XHS] waitForLoad: timeout ${timeout}ms for tab ${tabId}`);
      resolve();
    }, timeout);

    function listener(id, info) {
      if (id === tabId && info.status === 'complete') {
        clearTimeout(timer);
        chrome.tabs.onUpdated.removeListener(listener);
        resolve();
      }
    }
    chrome.tabs.onUpdated.addListener(listener);
  });
}

/**
 * Poll until the tab URL contains `pattern` AND status is 'complete',
 * OR until timeout. Used after clicking a note link to confirm navigation.
 */
async function waitForNavigation(tabId, noteId, timeout = 12000) {
  const start = Date.now();
  while (Date.now() - start < timeout) {
    try {
      const tab = await chrome.tabs.get(tabId);
      if (tab.url && tab.url.includes(noteId) && tab.status === 'complete') {
        return true;
      }
      // Also accept if URL has /explore/ even if noteId check fails
      if (tab.url && tab.url.includes('/explore/') && tab.status === 'complete') {
        return true;
      }
    } catch {}
    await sleep(400);
  }
  console.warn(`[XHS] waitForNavigation: timeout for note ${noteId}`);
  return false;
}

/**
 * Collect note IDs visible in the current search results page.
 * Returns an array of note ID strings (without tokens — tokens are
 * generated by XHS JS only when a link is actually clicked).
 */
async function getNoteIds(tabId) {
  const results = await chrome.scripting.executeScript({
    target: { tabId },
    func: () => {
      const anchors = document.querySelectorAll('a[href*="/explore/"]');
      const ids = [];
      anchors.forEach(a => {
        // Read the raw href attribute (not a.href which may be incomplete)
        const raw = a.getAttribute('href') || a.href || '';
        const m = raw.match(/\/explore\/([0-9a-zA-Z]+)/);
        if (m && !ids.includes(m[1])) ids.push(m[1]);
      });
      return ids;
    },
  });
  return results[0]?.result || [];
}

/**
 * Click the note link using chrome.debugger Input events (isTrusted: true).
 *
 * element.click() / dispatchEvent() produce isTrusted:false events, which
 * XHS detects and refuses to inject xsec_token for. The only way to produce
 * isTrusted:true clicks from an extension is via the Chrome DevTools Protocol
 * (chrome.debugger API), which goes through the browser's real input pipeline.
 *
 * Returns true if a link was found and clicked, false otherwise.
 */
async function clickNoteLink(tabId, noteId) {
  // Find the on-screen coordinates of the link element
  const posResult = await chrome.scripting.executeScript({
    target: { tabId },
    func: (id) => {
      const links = Array.from(document.querySelectorAll('a[href*="/explore/"]'))
        .filter(a => (a.getAttribute('href') || '').includes(id));
      if (!links.length) return null;
      const rect = links[0].getBoundingClientRect();
      // Clamp to visible area so the event lands inside the viewport
      return {
        x: Math.round(Math.max(1, Math.min(rect.left + rect.width / 2, window.innerWidth - 1))),
        y: Math.round(Math.max(1, Math.min(rect.top + rect.height / 2, window.innerHeight - 1))),
      };
    },
    args: [noteId],
  });

  const pos = posResult[0]?.result;
  if (!pos) {
    console.warn('[XHS] Link element not found for note:', noteId);
    return false;
  }

  const target = { tabId };
  try {
    await chrome.debugger.attach(target, '1.3');
  } catch (e) {
    // Already attached (e.g. from a previous failed attempt) — detach and retry
    console.warn('[XHS] Debugger attach failed, retrying:', e.message);
    await chrome.debugger.detach(target).catch(() => {});
    await sleep(200);
    await chrome.debugger.attach(target, '1.3');
  }

  try {
    // 1. Move mouse onto the element (triggers XHS hover handlers)
    await chrome.debugger.sendCommand(target, 'Input.dispatchMouseEvent', {
      type: 'mouseMoved', x: pos.x, y: pos.y, modifiers: 0,
    });
    await sleep(350); // give XHS time to react to hover (token prep)

    // 2. Press + release = real click with isTrusted:true
    await chrome.debugger.sendCommand(target, 'Input.dispatchMouseEvent', {
      type: 'mousePressed', x: pos.x, y: pos.y,
      button: 'left', clickCount: 1, modifiers: 0,
    });
    await chrome.debugger.sendCommand(target, 'Input.dispatchMouseEvent', {
      type: 'mouseReleased', x: pos.x, y: pos.y,
      button: 'left', clickCount: 1, modifiers: 0,
    });
  } finally {
    // Detach immediately — minimises the "DevTools is debugging" banner duration
    await chrome.debugger.detach(target).catch(() => {});
  }

  return true;
}

/**
 * Scrape the note content from the current page.
 */
async function scrapeCurrentPage(tabId, keyword, noteId) {
  const results = await chrome.scripting.executeScript({
    target: { tabId },
    func: (kw, expectedId) => {
      // Verify we're on the correct note page
      const match = location.pathname.match(/\/explore\/([0-9a-zA-Z]+)/);
      if (!match) return null;
      if (expectedId && match[1] !== expectedId) return null;

      // Abort on 404 / error pages
      if (location.pathname.includes('/404') ||
          document.title.includes('404') ||
          document.querySelector('.error-page')) {
        return null;
      }

      const noteId = match[1];

      function parseCount(el) {
        if (!el) return 0;
        const text = (el.textContent || '').trim().replace(/[,，]/g, '');
        if (text.endsWith('万')) return Math.round(parseFloat(text) * 10000);
        return parseInt(text) || 0;
      }

      const title = (
        document.querySelector('#detail-title') ||
        document.querySelector('.note-content .title') ||
        document.querySelector('h1')
      )?.textContent?.trim() || '';

      const content = (
        document.querySelector('#detail-desc') ||
        document.querySelector('.note-content .desc') ||
        document.querySelector('.desc')
      )?.textContent?.trim() || '';

      const author = (
        document.querySelector('.author-wrapper .name') ||
        document.querySelector('.username')
      )?.textContent?.trim() || '';

      const authorHref = (
        document.querySelector('.author-wrapper a') ||
        document.querySelector('a.author')
      )?.href || '';
      const authorIdMatch = authorHref.match(/\/user\/profile\/([0-9a-zA-Z]+)/);
      const authorId = authorIdMatch?.[1] || '';

      const likes = parseCount(
        document.querySelector('.like-wrapper .count') ||
        document.querySelector('[class*="like"] .count')
      );
      const collects = parseCount(
        document.querySelector('.collect-wrapper .count') ||
        document.querySelector('[class*="collect"] .count')
      );

      const dateEl =
        document.querySelector('.note-content .date') ||
        document.querySelector('time') ||
        document.querySelector('[class*="date"]');
      const publishDate = dateEl?.textContent?.trim() || '';

      const commentEls = document.querySelectorAll('.comment-item, .comments-el');
      const comments = [];
      commentEls.forEach((el, idx) => {
        if (idx >= 10) return;
        const c = (
          el.querySelector('.content') ||
          el.querySelector('.comment-content')
        )?.textContent?.trim() || '';
        const cl = parseCount(
          el.querySelector('.like-count') ||
          el.querySelector('[class*="like"]')
        );
        comments.push({
          id: `${noteId}_c_${idx + 1}`,
          note_id: noteId,
          content: c,
          likes: cl,
          rank: idx + 1,
        });
      });

      return {
        id: noteId, keyword: kw, title, content, author, author_id: authorId,
        likes, collects, publish_date: publishDate, url: location.href,
        source: 'dom', comments,
      };
    },
    args: [keyword, noteId],
  });
  return results[0]?.result || null;
}

/**
 * POST a batch of notes to the backend.
 */
async function pushNotes(notes) {
  const resp = await fetch(`${CONFIG.BACKEND_URL}/api/notes`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ notes }),
  });
  if (!resp.ok) throw new Error(`Backend error: ${resp.status}`);
  return resp.json();
}

/**
 * Process one keyword: click-navigate into each note, scrape, go back.
 * This approach lets XHS JS inject the xsec_token before navigation
 * (which does not happen when navigating by URL directly).
 */
async function processKeyword(tabId, keyword, maxNotes) {
  const searchUrl = `https://www.xiaohongshu.com/search_result?keyword=${encodeURIComponent(keyword)}&type=51`;

  // Navigate to search page
  await chrome.tabs.update(tabId, { url: searchUrl });
  await waitForLoad(tabId);
  await sleep(3000); // wait for dynamic content

  const collected = [];
  const seenIds = new Set();
  let scrollRound = 0;
  const maxScrollRounds = Math.ceil(maxNotes / 5) + 2;

  while (collected.length < maxNotes && scrollRound < maxScrollRounds) {
    if (stopRequested) break;

    // Get note IDs currently visible on search results page
    const ids = await getNoteIds(tabId);
    const newIds = ids.filter(id => !seenIds.has(id));

    for (const noteId of newIds) {
      if (stopRequested || collected.length >= maxNotes) break;
      seenIds.add(noteId);

      sendProgress(`关键词「${keyword}」: 正在抓取 ${collected.length + 1}/${maxNotes}...`);

      try {
        // Start waiting BEFORE clicking to avoid race condition where
        // the tab load event fires before we add the listener.
        const loadPromise = waitForLoad(tabId);

        // Click the link — XHS JS will inject xsec_token and navigate
        const clicked = await clickNoteLink(tabId, noteId);
        if (!clicked) {
          console.warn('[XHS] Link not found for note:', noteId);
          continue;
        }

        // Wait for navigation: prefer URL-based confirmation, fall back to load event
        const navigated = await waitForNavigation(tabId, noteId);
        if (!navigated) {
          // loadPromise timeout already resolved; try a fixed wait as last resort
          await loadPromise;
        }
        await sleep(2500); // wait for SPA async rendering after URL change

        // Verify we actually landed on the expected note page
        const tab = await chrome.tabs.get(tabId);
        console.log(`[XHS] Note tab URL: ${tab.url}`);
        if (tab.url && tab.url.includes('/404')) {
          console.warn('[XHS] Got 404 for note:', noteId, tab.url);
          // Fall through — scrape will return null and we'll skip
        }

        // Scrape
        const note = await scrapeCurrentPage(tabId, keyword, noteId);
        if (note) {
          collected.push(note);
          console.log(`[XHS] Scraped note ${noteId}: "${note.title}"`);
        } else {
          console.warn('[XHS] Scrape returned null for:', noteId, 'URL:', tab.url);
        }

        // Navigate back to search results
        await chrome.scripting.executeScript({
          target: { tabId },
          func: () => window.history.back(),
        });
        // Wait for search results to be restored
        await waitForLoad(tabId);
        await sleep(2000);

      } catch (e) {
        console.warn('Error scraping note', noteId, e);
        // Try to get back to search results if something went wrong
        try {
          await chrome.tabs.update(tabId, { url: searchUrl });
          await waitForLoad(tabId);
          await sleep(3000);
        } catch {}
      }

      await randomDelay();
    }

    // Scroll down to reveal more results
    await chrome.scripting.executeScript({
      target: { tabId },
      func: () => window.scrollBy({ top: 800, behavior: 'smooth' }),
    });
    scrollRound++;
    await sleep(2000);
  }

  return collected;
}

/**
 * Main task runner — processes all keywords sequentially.
 */
async function runTask(keywords, maxNotes) {
  stopRequested = false;
  chrome.storage.local.set({ taskRunning: true });

  const tab = await chrome.tabs.create({ url: 'about:blank', active: false });
  const tabId = tab.id;

  let totalDone = 0;

  try {
    for (const keyword of keywords) {
      if (stopRequested) break;

      sendProgress(`开始处理关键词「${keyword}」...`);

      const collected = await processKeyword(tabId, keyword, maxNotes);

      if (collected.length > 0) {
        try {
          await pushNotes(collected);
          totalDone += collected.length;
          sendProgress(`关键词「${keyword}」完成，共 ${collected.length} 篇`);
        } catch (e) {
          console.error('Backend push failed:', e);
          sendProgress(`关键词「${keyword}」推送后端失败: ${e.message}`);
        }
      } else {
        sendProgress(`关键词「${keyword}」未抓取到数据`);
      }
    }
  } finally {
    await chrome.tabs.remove(tabId).catch(() => {});
    sendDone(`采集完成！共采集 ${totalDone} 篇笔记`);
  }
}

// Message handler
chrome.runtime.onMessage.addListener((msg) => {
  if (msg.type === 'START_TASK') {
    runTask(msg.keywords, msg.maxNotes);
  }
  if (msg.type === 'STOP_TASK') {
    stopRequested = true;
  }
});
